### ISSUE TITLE
Errors in /etc/default/dns-reverse-proxy

### ISSUE THREAD

**Issue by Kandji94** [StalkR/dns-reverse-proxy#11]
Hello
I have errors when i configure /etc/deault/dns-reverse-proxy file:

/etc/init.d/dns-reverse-proxy: 1: /etc/default/dns-reverse-proxy: Arguments:: not found
/etc/init.d/dns-reverse-proxy: 2: /etc/default/dns-reverse-proxy: -address: not found
/etc/init.d/dns-reverse-proxy: 3: /etc/default/dns-reverse-proxy: -default: not found
/etc/init.d/dns-reverse-proxy: 4: /etc/default/dns-reverse-proxy: -route: not found
/etc/init.d/dns-reverse-proxy: 5: /etc/default/dns-reverse-proxy: -allow-transfer: not found

Do you have solution about this issue?

Thank you

**Comment by StalkR** [comment]
It seems your `/etc/default/dns-reverse-proxy` file is wrong, because these lines correspond to commented lines in https://github.com/StalkR/dns-reverse-proxy/blob/master/debian/dns-reverse-proxy.default
I would advise looking in this direction.
