### ISSUE TITLE
does not bind on IPv4?

### ISSUE THREAD

**Issue by mpictor** [StalkR/dns-reverse-proxy#3]
```bash
dns-reverse-proxy -address :53 -default #...
```

`lsof -i | grep domain`
```
dns-rever 17889            root    3u  IPv6 3927110      0t0  TCP *:domain (LISTEN)
dns-rever 17889            root    5u  IPv6 3927112      0t0  UDP *:domain
dns-rever 17889            root    6u  IPv6 3927112      0t0  UDP *:domain
dns-rever 17889            root    7u  IPv6 3927112      0t0  UDP *:domain
dns-rever 17889            root    8u  IPv6 3927112      0t0  UDP *:domain
dns-rever 17889            root    9u  IPv6 3927112      0t0  UDP *:domain
```

**Comment by StalkR** [comment]
Hi, listening on ":53" means listening on both IPv4 & IPv6. It shows in netstat/lsof as only IPv6, but if you try connecting from an IPv4 it should work. I don't think it's Go specific, more of a socket/Linux/Unix thing.
If you want to specifically bind on IPv4 / IPv6 I believe you can use 0.0.0.0.:53 / [::]:53.
Cheers

**Comment by mpictor** [comment]
whoops, when `dig @127.0.0.1 google.com` failed and I saw IPv6 in lsof output, I assumed that was the culprit.

Turned out the problem here was I had `-default dns.ip.ad.dr` instead of `-default dns.ip.ad.dr:53`.

If the port's missing, it seems to fail silently - nothing on stderr/stdout, doesn't exit, and dig's output is like

`dig @127.0.0.1 google.com`
```
; <<>> DiG 9.11.1-P3 <<>> @127.0.0.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 54575
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;google.com.                    IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 29 14:55:24 EST 2017
;; MSG SIZE  rcvd: 28
```

**Comment by mpictor** [comment]
Now I see that your examples all specify the port number. If you can't make it assume a default of :53, could you at least have a warning/error when no port is specified? This bit me on both `-default` and `-route`.

**Comment by StalkR** [comment]
This is where the DNS request is passed on to the specified default or route: https://github.com/StalkR/dns-reverse-proxy/blob/master/dns_reverse_proxy.go#L150
If invalid address because missing port, I'm guessing it can't connect, returns an error and responds with a DNS error, which you can see in the dig output with `status: SERVFAIL`.

Anyways, yes we can add some early sanity checking of the arguments being passed before starting the server, because missing port is definitely not good.
