### ISSUE TITLE
routes list should support multiple addresses

### ISSUE THREAD

**Issue by winteraz** [StalkR/dns-reverse-proxy#5]
A domain name usually has 2 name servers so I think the route flag should support multiple addresses (e.g. -route .example.com.=8.8.4.4:53_8.8.8.8:53 \)

**Comment by StalkR** [comment]
Yes, it could support it.

In terms of format I'm not sure about _, maybe , or ; would be better. Comma (,) is already taken to separate routes, but maybe we can swap it with ; like that: `-route .example.com=8.8.8.8:53,8.8.4.4:53;another=1.2.3.4:53`

In terms of implementation, it could be a simple round robin around the list or a random pick every time.
